### ISSUE TITLE
feat: add option to specify additional parameters on authorize endpoint

### ISSUE THREAD

**Issue by vdbulcke** [vdbulcke/oidc-client-demo#33]
# Descriptions

Same functionality as `par_additional_parameters:` but on the authorize request. For example: 
```yaml
### Arbitrary Key/Value parameters to include in Authorize request
authorize_additional_parameters:

  claims: '{"id_token": {"foo": {"values": ["bar", "baz"]}}}'
````
