### ISSUE TITLE
feature: Add support for OIDC Configuration without well known openid-configuration

### ISSUE THREAD

**Issue by vdbulcke** [vdbulcke/oidc-client-demo#7]
# Description

Add Support for Authorization Server that do not have well-known openid-configuration

## Configuration

```yaml
## Override config
disable_well_known_configuration: true
insecure_well_known_endpoint: "https://another.domain.than.issuer.com/.well-known/openid-configuration"
token_endpoint: "https://example.com/oauth2/access_token"
authorize_endpoint: "https://example.com/oauth2/authorize"
userinfo_endpoint: "https://example.com/oauth2/userinfo"
jwks_endpoint: "https://example.com/oauth2/jwk.json"
```

## Implementation

if `disable_well_known_configuration: true` then don't look up well known endpoint based on issuer url. 

 - 1 if  `insecure_well_known_endpoint: ` is defined, use lookup this alternative url. Using `InsecureIssuerURLContext`  (https://github.com/coreos/go-oidc/blob/v3/oidc/oidc.go#L87)
 - 2 if  `insecure_well_known_endpoint: ` is  not defined,  create  a `ProviderConfig` (https://github.com/coreos/go-oidc/blob/366ac4a7e8b3be7ff45e6e1b0e1ab2e43b47d4ee/oidc/oidc.go#L139) based on the the static endpoint defined in the config, and create the oidc provier with `func (p *ProviderConfig) NewProvider(ctx context.Context) *Provider ` https://github.com/coreos/go-oidc/blob/366ac4a7e8b3be7ff45e6e1b0e1ab2e43b47d4ee/oidc/oidc.go#L168
